include: package:flutter_lints/flutter.yaml

linter:
  rules:

dart_code_metrics:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - lib/generated_plugin_registrant.dart
    - lib/firebase/firebase_options.dart

  rules:
